import { injectable } from 'tsyringe';

@injectable()
export class CommonConfig {
    public getByKey(key: CommonConfigKeys): string {
        const value = process.env[key];
        return value || '';
    }

    public getAll(): NodeJS.ProcessEnv {
        return process.env;
    }
}

export enum CommonConfigKeys {
    SMS_CONNECTION_STRING = 'COMMUNICATION_SERVICES_CONNECTION_STRING',
    SMS_SOURCE_PHONE_NUMBER = 'COMMUNICATION_SERVICES_SOURCE_PHONE_NUMBER',
    STORAGE_CONNECTION_STRING = 'AZURE_STORAGE_CONNECTION_STRING',
    STORAGE_QUEUE_NAME = 'AZURE_STORAGE_QUEUE_NAME',
    AKV_LOCAL_CERT_PATH = 'AKV_LOCAL_CERT_PATH',
    LOADED_DOTENV_PATH = 'LOADED_DOTENV_PATH',
    AKV_SECRET_NAME = 'AZURE_KEY_VAULT_SECRET_NAME',
    AKV_NAME = 'AZURE_KEY_VAULT_NAME',
    AKV_TENANT_ID = 'AZURE_TENANT_ID',
    AKV_CLIENT_ID = 'AZURE_CLIENT_ID',
    SECRET_FILE_VER = 'SECRET_FILE_VER',
    OCTOPUS_API_KEY = 'OCTOPUS_API_KEY',
    OCTOPUS_HOST_STR = 'OCTOPUS_HOST_STR',
    PORT_TO_USE = 'PORT_TO_USE',
    HOST_TO_USE = 'HOST_TO_USE',
    OTEL_EXPORTER_OTLP_TRACES_AUTH = 'OTEL_EXPORTER_OTLP_TRACES_AUTH',
    OTEL_EXPORTER_OTLP_TRACES_ENDPOINT = 'OTEL_EXPORTER_OTLP_TRACES_ENDPOINT',
    OTEL_EXPORTER_OTLP_TRACES_EMAIL = 'OTEL_EXPORTER_OTLP_TRACES_EMAIL',
    MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING',
    MONGO_CLUSTER_NAME = 'MONGO_CLUSTER_NAME',
    MONGO_DB_NAME = 'MONGO_DB_NAME',
    MONGO_TABLE_NAME = 'MONGO_TABLE_NAME',
}
